<a href="https://colab.research.google.com/github/akorkos/Assignments-in-Algorithms/blob/main/alexkork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Φορτωμα των καταλληλων βιβλιθηκων

In [ ]:
import pandas as pd
import numpy as np
from mlxtend.preprocessing import TransactionEncoder

In [ ]:
data = pd.read_csv(r'GroceriesInitial.csv')
#print(data[(data["basket_value"] < 2.7)]['id'].count())
#print(data[(data["basket_value"] >= 2.7) & (data["basket_value"] < 5.8)]['id'].count())
#print(data[(data["basket_value"] >= 5.8)]['id'].count())
data['basket'] = ''
data.loc[data['basket_value'] <= 2.7, 'basket'] = 'low_value_basket'
data.loc[(data['basket_value'] > 2.7) & (data['basket_value'] <= 5.8), 'basket'] = 'medium_value_basket'
data.loc[data['basket_value'] > 5.8, 'basket'] = 'high_value_basket'

data = data.drop(columns=['id', 'basket_value', 'recency_days'])
data = data.fillna('')
transactionEncoder = TransactionEncoder()     
array = transactionEncoder.fit(data.values).transform(data.values)
array = np.delete(array, 0, 0)
array = np.delete(array, 0, 1)
transactionEncoder.columns_.pop(0)
d = pd.DataFrame(array, columns=transactionEncoder.columns_)
d = d[['low_value_basket', 'medium_value_basket', 'high_value_basket', 'citrus fruit','tropical fruit','whole milk','other vegetables','rolls/buns', 'chocolate', 'bottled water', 'yogurt', 'sausage', 'root vegetables', 'pastry', 'soda', 'cream']]

In [45]:
!pip install apyori

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting apyori
  Downloading apyori-1.1.2.tar.gz (8.6 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: apyori
  Building wheel for apyori (setup.py) ... done
  Created wheel for apyori: filename=apyori-1.1.2-py3-none-any.whl size=5976 sha256=57af48cf33d99c62a638866ce2820db41ecf65572bae93e42ec7c1d781103a3e
  Stored in directory: /root/.cache/pip/wheels/c4/1a/79/20f55c470a50bb3702a8cb7c94d8ada15573538c7f4baebe2d
Successfully built apyori
Installing collected packages: apyori
Successfully installed apyori-1.1.2

In [84]:
from apyori import apriori
from mlxtend.frequent_patterns import apriori, association_rules
# Intializing the list
# transacts = []
# populating a list of transactions
# for i in range(0, len(d)): 
  # transacts.append([str(data.values[i,j]) for j in range(0, 16)])

frequent_itemsets = apriori(d, min_support=0.03, use_colnames=True)
association_rules(frequent_itemsets, metric="confidence", min_threshold=0.6).sort_values(by=['confidence'], ascending=False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
21,"(soda, sausage)",(high_value_basket),0.031719,0.332449,0.031719,1.000000,3.007984,0.021174,inf
9,"(whole milk, sausage)",(high_value_basket),0.039018,0.332449,0.039018,1.000000,3.007984,0.026046,inf
19,"(rolls/buns, sausage)",(high_value_basket),0.039947,0.332449,0.039947,1.000000,3.007984,0.026667,inf
15,"(other vegetables, sausage)",(high_value_basket),0.035169,0.332449,0.035169,1.000000,3.007984,0.023477,inf
1,(sausage),(high_value_basket),0.122628,0.332449,0.107366,0.875541,2.633614,0.066598,5.363631
11,"(pastry, whole milk)",(high_value_basket),0.043397,0.332449,0.036629,0.844037,2.538849,0.022202,4.280183
5,"(yogurt, tropical fruit)",(high_value_basket),0.038222,0.332449,0.030524,0.798611,2.402209,0.017817,3.314738
3,"(whole milk, tropical fruit)",(high_value_basket),0.055209,0.332449,0.042468,0.769231,2.313834,0.024114,2.892723
4,"(other vegetables, tropical fruit)",(high_value_basket),0.046848,0.332449,0.035833,0.764873,2.300724,0.020258,2.839104
18,"(rolls/buns, yogurt)",(high_value_basket),0.044857,0.332449,0.033975,0.757396,2.278236,0.019062,2.751614
14,"(other vegetables, yogurt)",(high_value_basket),0.056669,0.332449,0.041539,0.733021,2.204916,0.022700,2.500390
13,"(other vegetables, rolls/buns)",(high_value_basket),0.055607,0.332449,0.040743,0.732697,2.203941,0.022257,2.497358
17,"(other vegetables, soda)",(high_value_basket),0.042734,0.332449,0.030259,0.708075,2.129877,0.016052,2.286719
16,"(root vegetables, other vegetables)",(high_value_basket),0.061845,0.332449,0.042734,0.690987,2.078478,0.022174,2.160271
8,"(whole milk, yogurt)",(high_value_basket),0.073125,0.332449,0.049768,0.680581,2.047176,0.025457,2.089891
20,"(rolls/buns, soda)",(high_value_basket),0.050033,0.332449,0.033577,0.671088,2.018621,0.016943,2.029572
2,(pastry),(high_value_basket),0.116125,0.332449,0.077372,0.666286,2.004177,0.038767,2.000368
12,"(soda, whole milk)",(high_value_basket),0.052289,0.332449,0.034771,0.664975,2.000233,0.017388,1.992540
10,"(root vegetables, whole milk)",(high_value_basket),0.063835,0.332449,0.042070,0.659044,1.982393,0.020848,1.957879
7,"(rolls/buns, whole milk)",(high_value_basket),0.073922,0.332449,0.048706,0.658887,1.981921,0.024131,1.956980
6,"(other vegetables, whole milk)",(high_value_basket),0.097678,0.332449,0.060252,0.616848,1.855468,0.027779,1.742262
0,(chocolate),(high_value_basket),0.064764,0.332449,0.039814,0.614754,1.849171,0.018283,1.732793

In [71]:
# rule = apriori(transactions = transacts, min_support = 0.03, min_confidence = 0.6) # min_lift = 3, min_length = 2, max_length = 2)

Empty DataFrame
Columns: [Left_Hand_Side, Right_Hand_Side, Support, Confidence, Lift]
Index: []